### ISSUE TITLE
angular6 build seems to be incomplete

### ISSUE THREAD

**Issue by unki** [7h4r05/ngx-message-bus#2]
Hello!

Thanks for merging my pull request #1 for the Angular6 support that swiftly!

But I need to tell you, that something must have gone wrong when you built the package and/or published it into the _npm repository_.

Because your _ngx-message-bus_ build fails to built with my Angular6 app.

```
ERROR in src/app/providers/auth.service.ts(27,40): error TS2307: Cannot find module 'ngx-message-bus'.
src/app/providers/login.service.ts(25,40): error TS2307: Cannot find module 'ngx-message-bus'.
src/app/components/online-checker/online-checker.component.ts(25,40): error TS2307: Cannot find module 'ngx-message-bus'.
src/app/app.module.ts(43,28): error TS2307: Cannot find module 'ngx-message-bus'.
```

It looks like the Angular compiler does not recognized _ngx-message-bus_ as an available module at all.

Otherwise - my own builds of _ngx-message-bus(@2.0.0)_ basically work.
So if I compare the directory contents of these two builds - this is from your build:

```
ngx-message-bus.module.ts
package.json
public_api.ts
README.md
src
```

This is the content of my build (I published it temporary under my scope as `@unki/ngx-message-bus` put will unpublish it soon):

```
bundles
dist
ngx-message-bus.module.ts
package.json
public_api.ts
README.md
src
```

Obviously the `bundles` and the `dist` directories are missing from your recent build.

And at least the file `ngx-message-bus.module.ts` tries to include something from that `bundles` directory - this include happens the same in your build as well in mine. But naturally in your case
it fails, as the `bundles` directory is not there.

But I have to admit, that I do not have a lot of experience with node-modules.

In general I noted, that the upgrade of the Angular eco-system (cli, compiler, compiler-cli, typescript, etc.) from 5 to 6 does not always happen that smooth.

For both my Angular6 app (upgrade 5->6) and _ngx-message-bus_ I had to use a pristine checkout and did a fresh dev-dependencies install (`npm install --only=dev`) - before I then run `npm run build` and `npm publish` on _ngx-message-bus_.

So perhaps this could solve the present issue.

**Comment by 7h4r05** [comment]
Version 2.0.2 has been published to npm. Please verify if it works for you now

**Comment by unki** [comment]
Works like a charm! Thank you very much!
