### ISSUE TITLE
ModuleWithProviders not imported from correct place

### ISSUE THREAD

**Issue by mr1upmachine** [7h4r05/ngx-message-bus#3]
https://github.com/7h4r05/ngx-message-bus/blob/f5dd93d80f857feaf2a008137e6808bf5c0cab9f/ngx-message-bus.module.ts#L5

This line seems to be giving issues when converting our application to Angular 8. We get an error stating that `@angular/core/src/metadata/ng_module` is not a valid path anymore. The fix should be to just changing this line to the supported path `import { ModuleWithProviders } from '@angular/core'`.

**Comment by 7h4r05** [comment]
Thanks for reporting the issue. ngx-message-bus will be updated for ng8 within 2-3 days.

**Comment by 7h4r05** [comment]
Should be fine now. Let me know if you have any more issues.
