### ISSUE TITLE
Incompatible dependencies for Angular 9+

### ISSUE THREAD

**Issue by markwilx** [7h4r05/ngx-message-bus#6]
When updating my Angular application from version 8 to version 9, I encountered the following error:

`$ ng update @angular/core@9 @angular/cli@9`
`Using package manager: 'npm'`
`Collecting installed dependencies...`
`Found 47 dependencies.`
`Fetching dependency metadata from registry...`
`                  Package "ngx-message-bus" has an incompatible peer dependency to "@angular/cli" (requires "^8.0.0", would install "9.1.13").`

I'm hopeful ngx-message-queue will work to Angular version 11 with a simple update of the dependencies.

Thanks!  This is a fantastic library.

Mark

**Comment by 7h4r05** [comment]
Hi,

version should be updated now to ng@11. Let me know if this works for you.

**Comment by markwilx** [comment]
Wow! That was fast.  Thank you.  I've successfully migrated from Angular 8 to Angular 9.  I had no problems with the new version of ngx-message-bus.  I wish everything else was as easy.  I'll continue migrating until I get to Angular 11, and I'll let you know if I encounter any problems.

**Comment by markwilx** [comment]
I've migrated my project from Angular 8 to 9 and from Angular 9 to 10.  I'm not ready to go to Angular 11.  I had challenges with some of the migration, but no problems at all with ngx-message-bus.  It's working great.  Thanks again for the quick turn-around updating this package!

**Comment by markwilx** [comment]
Following up for the record -- I have migrated my project from Angular 10 to 11.  I experienced no issues with ngx-message-bus.  Thanks again for the great package.
